# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: juke_box.proto for package 'jukebox'

require 'grpc'
require 'juke_box_pb'

module Jukebox
  module JukeBox
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'jukebox.JukeBox'

      rpc :PlaySong, SongRequest, SongResponse
    end

    Stub = Service.rpc_stub_class
  end
end
