# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: juke_box.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("juke_box.proto", :syntax => :proto3) do
    add_message "jukebox.Song" do
      optional :title, :string, 1
      optional :artist, :string, 2
    end
    add_message "jukebox.SongRequest" do
      optional :genre, :enum, 1, "jukebox.Genre"
    end
    add_message "jukebox.SongResponse" do
      optional :song, :message, 1, "jukebox.Song"
    end
    add_enum "jukebox.Genre" do
      value :POP, 0
      value :ROCK, 1
      value :JAZZ, 2
      value :CLASSIC, 3
    end
  end
end

module Jukebox
  Song = Google::Protobuf::DescriptorPool.generated_pool.lookup("jukebox.Song").msgclass
  SongRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("jukebox.SongRequest").msgclass
  SongResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("jukebox.SongResponse").msgclass
  Genre = Google::Protobuf::DescriptorPool.generated_pool.lookup("jukebox.Genre").enummodule
end
